#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YES_og.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ePower_test")]
	public partial class DBePowerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void Insertveh000(veh000 instance);
    partial void Updateveh000(veh000 instance);
    partial void Deleteveh000(veh000 instance);
    partial void Insertdev100(dev100 instance);
    partial void Updatedev100(dev100 instance);
    partial void Deletedev100(dev100 instance);
    #endregion
		
		public DBePowerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ePower_testConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBePowerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBePowerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBePowerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBePowerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<veh000> veh000
		{
			get
			{
				return this.GetTable<veh000>();
			}
		}
		
		public System.Data.Linq.Table<dev100> dev100
		{
			get
			{
				return this.GetTable<dev100>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.veh000")]
	public partial class veh000 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _veh_id;
		
		private string _veh_brand;
		
		private string _veh_type;
		
		private string _veh_model;
		
		private string _tw_sale;
		
		private string _spot_type_ac;
		
		private string _spot_type_dc;
		
		private string _crt_user;
		
		private System.DateTime _crt_date;
		
		private string _udp_user;
		
		private System.Nullable<System.DateTime> _upd_date;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onveh_idChanging(int value);
    partial void Onveh_idChanged();
    partial void Onveh_brandChanging(string value);
    partial void Onveh_brandChanged();
    partial void Onveh_typeChanging(string value);
    partial void Onveh_typeChanged();
    partial void Onveh_modelChanging(string value);
    partial void Onveh_modelChanged();
    partial void Ontw_saleChanging(string value);
    partial void Ontw_saleChanged();
    partial void Onspot_type_acChanging(string value);
    partial void Onspot_type_acChanged();
    partial void Onspot_type_dcChanging(string value);
    partial void Onspot_type_dcChanged();
    partial void Oncrt_userChanging(string value);
    partial void Oncrt_userChanged();
    partial void Oncrt_dateChanging(System.DateTime value);
    partial void Oncrt_dateChanged();
    partial void Onudp_userChanging(string value);
    partial void Onudp_userChanged();
    partial void Onupd_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onupd_dateChanged();
    #endregion
		
		public veh000()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veh_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int veh_id
		{
			get
			{
				return this._veh_id;
			}
			set
			{
				if ((this._veh_id != value))
				{
					this.Onveh_idChanging(value);
					this.SendPropertyChanging();
					this._veh_id = value;
					this.SendPropertyChanged("veh_id");
					this.Onveh_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veh_brand", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string veh_brand
		{
			get
			{
				return this._veh_brand;
			}
			set
			{
				if ((this._veh_brand != value))
				{
					this.Onveh_brandChanging(value);
					this.SendPropertyChanging();
					this._veh_brand = value;
					this.SendPropertyChanged("veh_brand");
					this.Onveh_brandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veh_type", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string veh_type
		{
			get
			{
				return this._veh_type;
			}
			set
			{
				if ((this._veh_type != value))
				{
					this.Onveh_typeChanging(value);
					this.SendPropertyChanging();
					this._veh_type = value;
					this.SendPropertyChanged("veh_type");
					this.Onveh_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veh_model", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string veh_model
		{
			get
			{
				return this._veh_model;
			}
			set
			{
				if ((this._veh_model != value))
				{
					this.Onveh_modelChanging(value);
					this.SendPropertyChanging();
					this._veh_model = value;
					this.SendPropertyChanged("veh_model");
					this.Onveh_modelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tw_sale", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string tw_sale
		{
			get
			{
				return this._tw_sale;
			}
			set
			{
				if ((this._tw_sale != value))
				{
					this.Ontw_saleChanging(value);
					this.SendPropertyChanging();
					this._tw_sale = value;
					this.SendPropertyChanged("tw_sale");
					this.Ontw_saleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spot_type_ac", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string spot_type_ac
		{
			get
			{
				return this._spot_type_ac;
			}
			set
			{
				if ((this._spot_type_ac != value))
				{
					this.Onspot_type_acChanging(value);
					this.SendPropertyChanging();
					this._spot_type_ac = value;
					this.SendPropertyChanged("spot_type_ac");
					this.Onspot_type_acChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spot_type_dc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string spot_type_dc
		{
			get
			{
				return this._spot_type_dc;
			}
			set
			{
				if ((this._spot_type_dc != value))
				{
					this.Onspot_type_dcChanging(value);
					this.SendPropertyChanging();
					this._spot_type_dc = value;
					this.SendPropertyChanged("spot_type_dc");
					this.Onspot_type_dcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_user", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string crt_user
		{
			get
			{
				return this._crt_user;
			}
			set
			{
				if ((this._crt_user != value))
				{
					this.Oncrt_userChanging(value);
					this.SendPropertyChanging();
					this._crt_user = value;
					this.SendPropertyChanged("crt_user");
					this.Oncrt_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_date", DbType="DateTime NOT NULL")]
		public System.DateTime crt_date
		{
			get
			{
				return this._crt_date;
			}
			set
			{
				if ((this._crt_date != value))
				{
					this.Oncrt_dateChanging(value);
					this.SendPropertyChanging();
					this._crt_date = value;
					this.SendPropertyChanged("crt_date");
					this.Oncrt_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_udp_user", DbType="VarChar(64)")]
		public string udp_user
		{
			get
			{
				return this._udp_user;
			}
			set
			{
				if ((this._udp_user != value))
				{
					this.Onudp_userChanging(value);
					this.SendPropertyChanging();
					this._udp_user = value;
					this.SendPropertyChanged("udp_user");
					this.Onudp_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upd_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> upd_date
		{
			get
			{
				return this._upd_date;
			}
			set
			{
				if ((this._upd_date != value))
				{
					this.Onupd_dateChanging(value);
					this.SendPropertyChanging();
					this._upd_date = value;
					this.SendPropertyChanged("upd_date");
					this.Onupd_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dev100")]
	public partial class dev100 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _type_id;
		
		private string _spot_ac_dc;
		
		private string _spot_type;
		
		private string _spot_type2;
		
		private string _crt_user;
		
		private System.DateTime _crt_date;
		
		private string _udp_user;
		
		private System.Nullable<System.DateTime> _upd_date;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontype_idChanging(int value);
    partial void Ontype_idChanged();
    partial void Onspot_ac_dcChanging(string value);
    partial void Onspot_ac_dcChanged();
    partial void Onspot_typeChanging(string value);
    partial void Onspot_typeChanged();
    partial void Onspot_type2Changing(string value);
    partial void Onspot_type2Changed();
    partial void Oncrt_userChanging(string value);
    partial void Oncrt_userChanged();
    partial void Oncrt_dateChanging(System.DateTime value);
    partial void Oncrt_dateChanged();
    partial void Onudp_userChanging(string value);
    partial void Onudp_userChanged();
    partial void Onupd_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onupd_dateChanged();
    #endregion
		
		public dev100()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int type_id
		{
			get
			{
				return this._type_id;
			}
			set
			{
				if ((this._type_id != value))
				{
					this.Ontype_idChanging(value);
					this.SendPropertyChanging();
					this._type_id = value;
					this.SendPropertyChanged("type_id");
					this.Ontype_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spot_ac_dc", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string spot_ac_dc
		{
			get
			{
				return this._spot_ac_dc;
			}
			set
			{
				if ((this._spot_ac_dc != value))
				{
					this.Onspot_ac_dcChanging(value);
					this.SendPropertyChanging();
					this._spot_ac_dc = value;
					this.SendPropertyChanged("spot_ac_dc");
					this.Onspot_ac_dcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spot_type", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string spot_type
		{
			get
			{
				return this._spot_type;
			}
			set
			{
				if ((this._spot_type != value))
				{
					this.Onspot_typeChanging(value);
					this.SendPropertyChanging();
					this._spot_type = value;
					this.SendPropertyChanged("spot_type");
					this.Onspot_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spot_type2", DbType="VarChar(1) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string spot_type2
		{
			get
			{
				return this._spot_type2;
			}
			set
			{
				if ((this._spot_type2 != value))
				{
					this.Onspot_type2Changing(value);
					this.SendPropertyChanging();
					this._spot_type2 = value;
					this.SendPropertyChanged("spot_type2");
					this.Onspot_type2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_user", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string crt_user
		{
			get
			{
				return this._crt_user;
			}
			set
			{
				if ((this._crt_user != value))
				{
					this.Oncrt_userChanging(value);
					this.SendPropertyChanging();
					this._crt_user = value;
					this.SendPropertyChanged("crt_user");
					this.Oncrt_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt_date", DbType="DateTime NOT NULL")]
		public System.DateTime crt_date
		{
			get
			{
				return this._crt_date;
			}
			set
			{
				if ((this._crt_date != value))
				{
					this.Oncrt_dateChanging(value);
					this.SendPropertyChanging();
					this._crt_date = value;
					this.SendPropertyChanged("crt_date");
					this.Oncrt_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_udp_user", DbType="VarChar(64)")]
		public string udp_user
		{
			get
			{
				return this._udp_user;
			}
			set
			{
				if ((this._udp_user != value))
				{
					this.Onudp_userChanging(value);
					this.SendPropertyChanging();
					this._udp_user = value;
					this.SendPropertyChanged("udp_user");
					this.Onudp_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upd_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> upd_date
		{
			get
			{
				return this._upd_date;
			}
			set
			{
				if ((this._upd_date != value))
				{
					this.Onupd_dateChanging(value);
					this.SendPropertyChanging();
					this._upd_date = value;
					this.SendPropertyChanged("upd_date");
					this.Onupd_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
