<?xml version="1.0" encoding="utf-8"?><Database Name="ePower_test" Class="DBePowerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=13.114.92.18;Initial Catalog=ePower_test;Persist Security Info=True;User ID=ePower_cn" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ePower_testConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.veh000" Member="veh000">
    <Type Name="veh000">
      <Column Name="veh_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="veh_brand" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="veh_type" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="veh_model" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="tw_sale" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="spot_type_ac" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="spot_type_dc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.zip000" Member="zip000">
    <Type Name="zip000">
      <Column Name="zip_id" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="country" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="district" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="addr" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="addr2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="zone" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="region" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="zip_type" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dev000" Member="dev000">
    <Type Name="dev000">
      <Column Name="device_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="device_type" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="device_supplier" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="device_model" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="device_SN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="device_place" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="device_size" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="device_iplv" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="charger_qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="charger_type" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="charger_comm" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="charger_prot" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="charger_ac_dc" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="charger_plug" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="charger_current" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="charger_voltage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="charger_outputpower" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="note1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="device_status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="device_code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dev100" Member="dev100">
    <Type Name="dev100">
      <Column Name="type_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="spot_ac_dc" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="spot_type" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="spot_type2" Type="System.String" DbType="VarChar(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.stn005" Member="stn005">
    <Type Name="stn005">
      <Column Name="picmst_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="station_id" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="station_pic" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="pic_status" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.stn002" Member="stn002">
    <Type Name="stn002">
      <Column Name="station_id" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="chargespot_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="system_id" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="open_status" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.stn004" Member="stn004">
    <Type Name="stn004">
      <Column Name="chargespot_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="station_id" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="week_start" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="week_end" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="time_start" Type="System.String" DbType="NVarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="time_end" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="cal_unit" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="cal_freq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cost" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="fee_time_start" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fee_time_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="prepaid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rate_name" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.sts000" Member="sts000">
    <Type Name="sts000">
      <Column Name="item_id" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="prog_id" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fun_id" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="item_seq" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="item_desc" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="item_lv" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.cnc000" Member="cnc000">
    <Type Name="cnc000">
      <Column Name="cnc_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="veh_brand" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="contact_person" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="contact_mobile" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="contact_email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="install_address" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="zip_id" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="loc_class" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="contact_time" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="dealer_name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="sales_info" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="note" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="note1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="cnc_status" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.cnc002" Member="cnc002">
    <Type Name="cnc002">
      <Column Name="file_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cnc_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="File_name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="File_path" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="file_type" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="file_status" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.cnc001" Member="cnc001">
    <Type Name="cnc001">
      <Column Name="record_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cnc_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="survey_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="install_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="note1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="cnc_status" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.stn101" Member="stn101">
    <Type Name="stn101">
      <Column Name="tran_no" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="station_id" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="chargespot_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="device_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dely_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="device_sn" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="acpt_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="wty_start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="wty_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.stn102" Member="stn102">
    <Type Name="stn102">
      <Column Name="network_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="network_no" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="network_sn" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="network_supplier" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="network_type" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="station_id" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="network_ip" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="network_gateway" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="network_fee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="device_place" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="active_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="netwoek_note" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="network_status" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="network_note" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.cus000" Member="cus000">
    <Type Name="cus000">
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customer_fullname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="customer_class" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="company_branch" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="customer_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="company_principal" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="customer_type" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="customer_gender" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="contact_person" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="contact_mobile" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="contact_lineid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="contact_email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="customer_phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="customer_phone2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="customer_fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="company_service_phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="customer_address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="customer_zip" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="customer_guid" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="bank_code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="bank_account" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="note1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="supplier_status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.sup000" Member="sup000">
    <Type Name="sup000">
      <Column Name="supplier_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="company_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="company_fullname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="company_principal" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="contact_person" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="contact_mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="contact_lineid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="contact_email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="company_phone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="company_phone2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="company_fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="company_addr" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="company_zip" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tax_id" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="bank_code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="bank_account" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="note1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="supplier_status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.stn000" Member="stn000">
    <Type Name="stn000">
      <Column Name="station_id" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="station_owner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="station_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="station_address" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="station_gate_address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="station_type" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="station_class" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="station_zip" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="station_longitude" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="station_latitude" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="station_gate_pic" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="station_parking_pic" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="station_floor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="station_car_space" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="contact_person_local" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="contact_mobile_local" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="customer_phone2_local" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="contact_email_local" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="contact_lineid_local" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="contact_fax_local" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="station_note" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="station_note1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="station_status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.stn001" Member="stn001">
    <Type Name="stn001">
      <Column Name="chargespot_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="station_id" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="device_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="chargespot_seq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="chargegun_seq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="spot_floor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="spot_car_space" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="spot_note" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="spot_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.stn003" Member="stn003">
    <Type Name="stn003">
      <Column Name="station_id" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="week" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="time_start" Type="System.String" DbType="NVarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="time_end" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="crt_user" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="crt_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="udp_user" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="upd_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>